/**
 * Text File Processing API
 * Text File Processing API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import java.time.LocalDate
import org.openapitools.client.core.ApiModel

case class TextFile (
  taskId: Option[String] = None,
  taskCreationDate: Option[LocalDate] = None,
  fileId: Option[String] = None,
  taskStatus: Option[TextFileEnums.TaskStatus] = None,
  ips: Option[Seq[String]] = None
) extends ApiModel

object TextFileEnums {

  type TaskStatus = TaskStatus.Value
  object TaskStatus extends Enumeration {
    val Created = Value("created")
    val Completed = Value("completed")
  }

}
